---
title: Notes on development | Robin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: development@robinwinslow.co.uk
permalink: pretty
description: 'Quick posts about software development. I like to focus on open source,
  web technologies, devops and security.

'
markdown: kramdown
