name: "Set Issue Label"
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]

jobs:
  test:
    if: github.event.issue.comment.author == "webteam-app"
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["help", "wanted"]'
          labels: '["help wanted"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
