name: "Set Issue Label"
on:
  issue_comment:
    types: [created, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["help", "wanted"]'
          labels: '["help wanted"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
